[package]
name = "wasm-utils"
version = "0.1.4"
authors = ["Nikolay Volf <nikvolf@gmail.com>", "Sergey Pepyakin <s.pepyakin@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Collection of command-line utilities and corresponding Rust api for producing pwasm-compatible executables"
keywords = ["wasm", "webassembly", "pwasm"]

[dependencies]
parity-wasm = "0.27"
log = "0.3"
env_logger = "0.4"
lazy_static = "0.2"
clap = "2.24"
glob = "0.2"
byteorder = "1"

[dev-dependencies]
tempdir = "0.3"
wabt = "0.2"
diff = "0.1.11"

[lib]

[[bin]]
name = "wasm-prune"
path = "prune/main.rs"

[[bin]]
name = "wasm-ext"
path = "ext/main.rs"

[[bin]]
name = "wasm-gas"
path = "gas/main.rs"

[[bin]]
name = "wasm-build"
path = "build/main.rs"

[[bin]]
name = "wasm-stack-height"
path = "stack_height/main.rs"
